[package]
edition = "2021"
name = "ensure_no_std"
version = "0.0.0"
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
exit-no-std = "0.1.0"
panicking = { path = "..", default-features = false, features = ["abort"] }
